### ISSUE TITLE
Bootstrap v4  compatibility

### ISSUE THREAD

**Issue by poseso** [nakupanda/bootstrap3-dialog#314]
I have a project with Bootstrap v4, when I try to use the bootstrap dialog i get the following error:

Uncaught TypeError: Cannot call a class as a function

with bootstrap.js 3.3.7 it works fine but with bootstrap.js of v4 it throws that error, is there a workaround for this?

this is the complete error:

bootstrap.js:36 Uncaught TypeError: Cannot call a class as a function
    at _classCallCheck (http://contasoft.local/global/vendor/bootstrap/bootstrap.js:36:99)
    at BootstrapDialogModal.Modal (http://contasoft.local/global/vendor/bootstrap/bootstrap.js:1746:7)
    at new BootstrapDialogModal (http://contasoft.local/global/js/bootstrap-dialog.js:43:15)
    at BootstrapDialog.realize (http://contasoft.local/global/js/bootstrap-dialog.js:1067:46)
    at BootstrapDialog.open (http://contasoft.local/global/js/bootstrap-dialog.js:306:40)
    at Function.BootstrapDialog.show (http://contasoft.local/global/js/bootstrap-dialog.js:1126:45)
    at confirm_dialog (http://contasoft.local/admin/clients:688:29)
    at HTMLAnchorElement.<anonymous> (http://contasoft.local/admin/clients:682:13)
    at HTMLDocument.dispatch (http://contasoft.local/global/vendor/jquery/jquery.js:4737:27)
    at HTMLDocument.elemData.handle (http://contasoft.local/global/vendor/jquery/jquery.js:4549:28)

**Comment by nakupanda** [comment]
Sorry, I have no workaround to suggest :(

**Comment by poseso** [comment]
ok thank you i'll use sweet alert in the mean time, ill close this

**Comment by nakupanda** [comment]
Ok, sorry for the inconvenience.
